const locales = {
    heb: {
        'KinderYA': 'הקינדרייה',
        'Home': 'בית',
        'Admin': 'גננות',
        'Log In': 'התחברי',
        'Log Out': 'התנתקי',
        'Admin Panel': 'לגננת',
        'Admin Main Content Area': 'רשימת הילדים בגננו',
        'Admin Side Bar': 'הודעות מההורים',
        'All': 'כולם',
        'Present': 'נוכחים',
        'Absent': 'נפקדים',
        'Status': 'סטטוס',
        'In class': 'נוכח',
        'NOT IN CLASS': 'נפקד',
        'Last seen': 'נראה לאחרונה',
        'Kid properties': 'פרטי ילד',
        'Parents details': 'פרטי הורים',
        'Ok': '',
        'Cancel': '',
        'Reset': '',
        'Kid list area': '',
        'Lost your password': '',
        'Welcome': 'בגננו הקט',
        'Note Title': 'הודעה',
        'Notes panel': 'הודעות אחרונות',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',
        '': '',
        '': ''
    }
}

export default locales